.TH NEVOW-XMLGETTEXT "1" "Feb 2005" "" ""
.SH NAME
nevow-xmlgettext \- extract translatable strings
.SH SYNOPSIS
.B nevow\-xmlgettext
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH DESCRIPTION
Extract translatable strings from Nevow XML template files.
List files to process on command line.
Will output strings in PO format to standard output.
.TP
\fB\--help\fR 
Display usage information.
.TP
\fB\--version\fR 
Output version information and exit.
.SH AUTHOR
Written by Tommi Virtanen.
.SH "REPORTING BUGS"
Report bugs to <twisted-web@twistedmatrix.com>.
.SH COPYRIGHT
Copyright \(co 2005 Tommi Virtanen
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
gettext(1)
